### ISSUE TITLE
[mazer] incorrect dependencies for DebOps roles

### ISSUE THREAD

**Issue by nqb** [debops/debops#849] opened 2019-06-25 09:04 UTC
Hello,

If you try to use `mazer` to install `debops` collection and use it after in a playbook, you got an error with roles that has dependencies.

### Steps to reproduce
```console
$ mazer install debops.debops
$ mkdir ~/ansible; cd ~/ansible
$ touch site.yml hosts
```

`site.yml`
```yaml
- name: test DebOps collections
  hosts: ['debops_service_roundcube']
  become: True

  roles:
   - "debops.debops.roundcube"
```

`hosts`
```ini
[debops_service_roundcube]
localhost ansible_connection=local
```

```console
$ ansible-playbook site.yml -i hosts
```
### Actual results

```console
ERROR! the role 'debops.secret' was not found in /home/vagrant/ansible/roles:/home/vagrant/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/vagrant/.ansible/collections/ansible_collections/debops/debops/roles:/home/vagrant/ansible

The error appears to be in '/home/vagrant/.ansible/collections/ansible_collections/debops/debops/roles/roundcube/meta/main.yml': line 5, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - role: debops.secret
    ^ here
```

### Expected results

Role `debops.secret` should be found.

### Solution

Because all roles directories in the collection doesn't contain the `debops.` prefix (i.e. `roundcube` in place of `debops.roundcube`), dependencies should be:

```yaml
dependencies:

  - role: secret
```

We need to adjust the make process for collections. @drybjed, I will let you do it.

**Comment by drybjed** [comment] 2019-06-25 09:32
Agreed, it's probably the best course of action for now. In the future (most likely DebOps `v2.0.0`) the roles will be renamed, when the situation with Galaxy Collections is stable. I'll see what can be done.

**Comment by drybjed** [comment] 2019-06-25 10:45
Status: failed
Version: 1.0.4
Error Message: Expecting dependency name format to match "username.role_name", got secret

Well, this is what you get without testing remote services... OK, v1.0.5 will be released shortly, hopefully I'll get it right this time.

**Comment by nqb** [comment] 2019-06-25 11:33
@drybjed,

Sorry. My fix was working after importing collection to launch a role..
Perhaps some help here: https://github.com/ansible/galaxy/issues/1902

**Comment by nqb** [comment] 2019-06-25 11:57
@drybjed,

you can try on https://galaxy-dev.ansible.com

**Comment by drzraf** [comment] 2019-07-03 19:42
First try of debops.
* updated ansible
* installed mazer
* `mazer install debops.debops`
* Run my role (`debops.gitlab_runner`) ===> **Failed the same way.**

Note that changing `roles_path` in `ansible.cfg` does not work either because of the structure of `debops/` directory.
IMHO, `mazer` should really & quickly be embraced by this project as the first installation method.


(ugly) workaround: go into your `ansible_collections/debops/debops/roles` directory then `for i in *; do ln -s $i debops.$i; done` and append this in `roles_path`.

**Comment by drybjed** [comment] 2019-07-03 20:35
@drzraf It seems that [Ansible Galaxy service does not support roles with dependencies at the moment](https://github.com/ansible/galaxy/issues/1938). Believe me, I tried really hard to embrace `mazer`, but it keeps changing on me from time to time.

For example, your workaround to change the role directory names to `debops.*/` wouldn't have to be needed if Ansible Galaxy supported role directory names with dots - but it doesn't, and I specifically [have to rename the roles](https://github.com/debops/debops/blob/master/lib/mazer/make-collection#L52) to strip the `debops.` prefix from their directories for Ansible Galaxy to even allow to import a collection. On the other hand, Ansible Galaxy does not allow roles with dependencies that use either `<role_name>` or `<namespace>.<collection>.<role_name>` as the dependency name. So as you can see, currently dependencies in Galaxy are horribly broken.

On the other hand, because DebOps is focused on Debian, I'd like to support Ansible 2.7 for at least a year because that's the version included in Debian Buster. I'm not sure if renaming roles to `debops.debops.<role_name>` will work with the older Ansible version, I guess that I'll have to check. But alas, it's currently pointless because of the above issues with Ansible Galaxy.

Therefore, if you want to try out DebOps, I suggest that you use [other installation methods](https://docs.debops.org/en/master/user-guide/install.html), either via a `pip` package, or installing the repository from GitHub. These should work fine on Ansible 2.7 and Ansible 2.8 for the moment.

**Comment by nqb** [comment] 2019-07-04 05:20
For information, with Ansible 2.8, it's possible to use roles in debops collection which don't have dependencies.

**Comment by Dutchy-** [comment] 2019-09-02 10:57
This is currently breaking our build due to a dependency from mariadb_server, what is the recommended workaround?

**Comment by drybjed** [comment] 2019-09-02 11:08
@Dutchy-: you could install the DebOps monorepo directly from GitHub to a path in the filesystem somewhere and add it to the `roles_path` parameter in the `ansible.cfg` configuration file. Or you can install the `debops` package from PyPI and use the `debops` command to run Ansible playbooks, which basically does the same thing. See the installation instructions linked above for more details.

**Comment by Dutchy-** [comment] 2020-01-09 15:08
It broke again today, presumably due to recent changes. I used the following workaround in my CI today:

```
ansible-galaxy collection install debops.debops
sed -i -- 's/debops\.secret/secret/g' $HOME/.ansible/collections/ansible_collections/debops/debops/roles/mariadb_server/meta/main.yml
sed -i -- 's/debops\.secret/secret/g' $HOME/.ansible/collections/ansible_collections/debops/debops/roles/mariadb/meta/main.yml
```

Hope this helps

**Comment by Dutchy-** [comment] 2020-02-04 11:38
With the recent rename of all the roles and the removal of explicit dependencies in meta.yml, the secret dependency is no longer broken for me. 

PS. I found out after the move to roles01 etc, so my CI broke again, but that is unrelated.

**Comment by drybjed** [comment] 2020-02-04 12:07
@Dutchy- Good to hear. I hope that changes in DebOps Collections weren't too disruptive for you.

**Comment by Dutchy-** [comment] 2020-02-04 12:12
It was easy to fix, but I haven't found the correct way to set the `roles_path` automatically with ansible-galaxy collections, so I had to update it in `ansible.cfg` like so:

```
roles_path = $HOME/.ansible/roles:$HOME/.ansible/collections/ansible_collections/debops/debops/roles/:$HOME/.ansible/collections/ansible_collections/debops/roles01/roles/:$HOME/.ansible/collections/ansible_collections/debops/roles02/roles/:$HOME/.ansible/collections/ansible_collections/debops/roles03/roles/
```

I hope this helps any future readers.

**Comment by Legogris** [comment] 2020-02-25 07:19
I had no luck with this with the `cryptsetup` role after galaxy install.. Ugly solution is merging dependencies into one folder:
`cp -r  vendor/ansible_collections/debops/debops/roles/* vendor/ansible_collections/debops/roles03/roles`

**Comment by drybjed** [comment] 2020-02-25 07:44
@Legogris Can you tell a bit more details? How did you install DebOps connection, what were the error messages when you try to run the `cryptsetup` role, how did you run it?

**Comment by drybjed** [comment] 2020-02-25 08:57
It seems that the issue is in Ansible itself: https://github.com/ansible/ansible/issues/67723

**Closed as completed** 2020-03-03 08:25 UTC
Labels: bug, priority: medium
