### ISSUE TITLE
ACME Support fails

### ISSUE THREAD

**Issue by pdobrigkeit** [debops/debops#1281] opened 2020-02-25 11:11 UTC
Hey, I am trying to setup a Debian 10 Host including ACME support for my nginx servers

I have found the following in the error.log file in the acme folder of the realm:
/usr/bin/env: ‘python’: No such file or directory

Only `python3` is available. Is this a problem because of Debian 10?

**Comment by drybjed** [comment] 2020-02-25 19:04
The problem is two-fold - from Debian 10, DebOps does not install Python 2.7 packages by default because Python 2.7 has reached end of life. The installation of various Python 2.7 packages will be done if DebOps detects Python 2.7 already installed on the host, or you set in the inventory a variable:
```yaml
python__v2: True
```
The other side of the coin is that the `acme-tiny` script from upstream [still uses `#!/usr/bin/env python` as the interpreter](https://github.com/diafygi/acme-tiny/pull/240). Since at the moment the `pki` role in DebOps installs `acme-tiny` from upstream, this issue occurs on Debian 10 hosts. There is [an `acme-tiny` package in Buster](https://packages.debian.org/buster/acme-tiny) and I plan to switch to it instead of installing from upstream; I just haven't gotten around to it yet. Sorry about that.

As a temporary fix, if you update the shebang in the installed `acme-tiny` script, it should start working. Remove the PKI realm you created on the host and re-run the `pki` role:
```
debops service/pki -l host
```
This should do the trick.

**Comment by axl8713** [comment] 2020-05-20 08:38
Since the proposed workaround makes ansible complain about the modification in the installed `acme-tiny`script (`"Local modifications exist in repository (force=no)"`), I fixed the problem creating a symbolic link to python3:
```
ln -s /usr/bin/python3 /usr/bin/python
```
On Ubuntu 20.04, this makes `acme-tiny` run happily without editing it.

**Comment by drybjed** [comment] 2020-08-27 22:55
This issue should be fixed by https://github.com/debops/debops/pull/1489 which will be backported to stable DebOps releases. Closing.

**Closed as completed** 2020-08-27 22:58 UTC
Labels: bug, priority: high, tag: Let's Encrypt/ACME, tag: PKI, tag: Python
